/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactId = number;
export interface ContactRequest {
  'id' : ContactId,
  'city' : string,
  'name' : string,
  'mobileNumber' : string,
  'message' : string,
}
export interface Job {
  'id' : JobId,
  'title' : string,
  'salary' : [] | [string],
  'jobType' : [] | [string],
  'city' : string,
  'description' : string,
  'company' : string,
  'category' : JobCategory,
}
export type JobCategory = { 'other' : string } |
  { 'telecaller' : null } |
  { 'backOffice' : null } |
  { 'delivery' : null } |
  { 'warehouse' : null } |
  { 'fieldExec' : null };
export type JobId = number;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateJob' : ActorMethod<[JobId], undefined>,
  'addJob' : ActorMethod<
    [string, string, string, JobCategory, string, [] | [string], [] | [string]],
    JobId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateJob' : ActorMethod<[JobId], undefined>,
  'getAllActiveJobs' : ActorMethod<[], Array<Job>>,
  'getAllContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobById' : ActorMethod<[JobId], [] | [Job]>,
  'getJobsByCategory' : ActorMethod<[JobCategory], Array<Job>>,
  'getJobsByCity' : ActorMethod<[string], Array<Job>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobsByKeyword' : ActorMethod<[string], Array<Job>>,
  'seedExampleJobs' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], ContactId>,
  'updateJob' : ActorMethod<
    [
      JobId,
      string,
      string,
      string,
      JobCategory,
      string,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];