/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Nat32;
export const JobCategory = IDL.Variant({
  'other' : IDL.Text,
  'telecaller' : IDL.Null,
  'backOffice' : IDL.Null,
  'delivery' : IDL.Null,
  'warehouse' : IDL.Null,
  'fieldExec' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'salary' : IDL.Opt(IDL.Text),
  'jobType' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : JobCategory,
});
export const ContactId = IDL.Nat32;
export const ContactRequest = IDL.Record({
  'id' : ContactId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateJob' : IDL.Func([JobId], [], []),
  'addJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobCategory,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [JobId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateJob' : IDL.Func([JobId], [], []),
  'getAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getJobsByCategory' : IDL.Func([JobCategory], [IDL.Vec(Job)], ['query']),
  'getJobsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'seedExampleJobs' : IDL.Func([], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactId],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        JobId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobCategory,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Nat32;
  const JobCategory = IDL.Variant({
    'other' : IDL.Text,
    'telecaller' : IDL.Null,
    'backOffice' : IDL.Null,
    'delivery' : IDL.Null,
    'warehouse' : IDL.Null,
    'fieldExec' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'salary' : IDL.Opt(IDL.Text),
    'jobType' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : JobCategory,
  });
  const ContactId = IDL.Nat32;
  const ContactRequest = IDL.Record({
    'id' : ContactId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateJob' : IDL.Func([JobId], [], []),
    'addJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobCategory,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [JobId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateJob' : IDL.Func([JobId], [], []),
    'getAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobById' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getJobsByCategory' : IDL.Func([JobCategory], [IDL.Vec(Job)], ['query']),
    'getJobsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'seedExampleJobs' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactId],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          JobId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobCategory,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };