/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactRequest {
    id: ContactId;
    city: string;
    name: string;
    mobileNumber: string;
    message: string;
}
export interface Job {
    id: JobId;
    title: string;
    salary?: string;
    jobType?: string;
    city: string;
    description: string;
    company: string;
    category: JobCategory;
}
export type JobId = number;
export type JobCategory = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "telecaller";
    telecaller: null;
} | {
    __kind__: "backOffice";
    backOffice: null;
} | {
    __kind__: "delivery";
    delivery: null;
} | {
    __kind__: "warehouse";
    warehouse: null;
} | {
    __kind__: "fieldExec";
    fieldExec: null;
};
export type ContactId = number;
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateJob(jobId: JobId): Promise<void>;
    addJob(title: string, company: string, city: string, category: JobCategory, description: string, salary: string | null, jobType: string | null): Promise<JobId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateJob(jobId: JobId): Promise<void>;
    getAllActiveJobs(): Promise<Array<Job>>;
    getAllContactRequests(): Promise<Array<ContactRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobById(jobId: JobId): Promise<Job | null>;
    getJobsByCategory(category: JobCategory): Promise<Array<Job>>;
    getJobsByCity(city: string): Promise<Array<Job>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchJobsByKeyword(keyword: string): Promise<Array<Job>>;
    seedExampleJobs(): Promise<void>;
    submitContact(name: string, mobileNumber: string, city: string, message: string): Promise<ContactId>;
    updateJob(jobId: JobId, title: string, company: string, city: string, category: JobCategory, description: string, salary: string | null, jobType: string | null): Promise<void>;
}
import type { Job as _Job, JobCategory as _JobCategory, JobId as _JobId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateJob(arg0);
            return result;
        }
    }
    async addJob(arg0: string, arg1: string, arg2: string, arg3: JobCategory, arg4: string, arg5: string | null, arg6: string | null): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateJob(arg0);
            return result;
        }
    }
    async getAllActiveJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveJobs();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveJobs();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactRequests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobById(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByCategory(arg0: JobCategory): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCategory(to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCategory(to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByCity(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCity(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCity(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchJobsByKeyword(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobsByKeyword(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobsByKeyword(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedExampleJobs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedExampleJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedExampleJobs();
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ContactId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateJob(arg0: JobId, arg1: string, arg2: string, arg3: string, arg4: JobCategory, arg5: string, arg6: string | null, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_JobCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_JobCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobCategory): JobCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    title: string;
    salary: [] | [string];
    jobType: [] | [string];
    city: string;
    description: string;
    company: string;
    category: _JobCategory;
}): {
    id: JobId;
    title: string;
    salary?: string;
    jobType?: string;
    city: string;
    description: string;
    company: string;
    category: JobCategory;
} {
    return {
        id: value.id,
        title: value.title,
        salary: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.salary)),
        jobType: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.jobType)),
        city: value.city,
        description: value.description,
        company: value.company,
        category: from_candid_JobCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    telecaller: null;
} | {
    backOffice: null;
} | {
    delivery: null;
} | {
    warehouse: null;
} | {
    fieldExec: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "telecaller";
    telecaller: null;
} | {
    __kind__: "backOffice";
    backOffice: null;
} | {
    __kind__: "delivery";
    delivery: null;
} | {
    __kind__: "warehouse";
    warehouse: null;
} | {
    __kind__: "fieldExec";
    fieldExec: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "telecaller" in value ? {
        __kind__: "telecaller",
        telecaller: value.telecaller
    } : "backOffice" in value ? {
        __kind__: "backOffice",
        backOffice: value.backOffice
    } : "delivery" in value ? {
        __kind__: "delivery",
        delivery: value.delivery
    } : "warehouse" in value ? {
        __kind__: "warehouse",
        warehouse: value.warehouse
    } : "fieldExec" in value ? {
        __kind__: "fieldExec",
        fieldExec: value.fieldExec
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n7(_uploadFile, _downloadFile, x));
}
function to_candid_JobCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobCategory): _JobCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "telecaller";
    telecaller: null;
} | {
    __kind__: "backOffice";
    backOffice: null;
} | {
    __kind__: "delivery";
    delivery: null;
} | {
    __kind__: "warehouse";
    warehouse: null;
} | {
    __kind__: "fieldExec";
    fieldExec: null;
}): {
    other: string;
} | {
    telecaller: null;
} | {
    backOffice: null;
} | {
    delivery: null;
} | {
    warehouse: null;
} | {
    fieldExec: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "telecaller" ? {
        telecaller: value.telecaller
    } : value.__kind__ === "backOffice" ? {
        backOffice: value.backOffice
    } : value.__kind__ === "delivery" ? {
        delivery: value.delivery
    } : value.__kind__ === "warehouse" ? {
        warehouse: value.warehouse
    } : value.__kind__ === "fieldExec" ? {
        fieldExec: value.fieldExec
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
